<a href="https://colab.research.google.com/github/HYEEYH/my_study/blob/main/20230502.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- 함수 스왑 연습하기

In [ ]:
# def swap_value(x,y):
#     temp = x
#     x = y
#     y = temp

# def swap_offset(offset_x, offset_y):
#     temp = a[offset_x]
#     a[offset_x] = a[offset_y]
#     a[offset_y] = temp

# def swap_reference(list, offset_x, offset_y):
#     temp = list[offset_x]
#     list[offset_x] = list[offset_y]
#     list[offset_y] = temp

# a = [1,2,3,4,5]
# swap_value(a[1], a[2])
# print(a)

# swap_offset(1,2)
# print(a)

# swap_reference(a,1,2)
# print(a)

문1. 
- 두개의 숫자를 input으로 받으면 앞의 숫자를 뒤의 숫자로 나누는 함수
- 나눗셈을 한 후에는 몫과 나머지 순으로 튜플 값을 반환한다.

In [3]:
# 나의 풀이 - 뭔가 안됨.

def div(a,b):
    a = int(input("숫자입력1: "))
    b = int(input("숫자입력2: "))
    num1 = a//b
    num2 = a%b
    tuple_1 = (num2, num1)
    print(tuple_1)

IndentationError: ignored

##### 225p
문1-1 )두개의숫자를 input으로 받으면 작은수로 큰수를 나는 목과 나머지를 반환하는 함수 만들기
- 반환값은 튜플로 되어있으며 몫, 나머지 순으로 되어있다
- 단, 0으로 나누는것은 불가. 두 수 중 작은수가 0이라면 화면에 0은 사용할수 없다를 출력하고 종료되어야 한다

In [ ]:
def div3(a,b):
    if a<b:
        big = b
        samll = a
    elif b<=a:
        big = a
        small = b
    else:
        print("정수가 아닙니다")
    if small == 0:
        print("0은 사용할 수 없습니다.")
    elif abs(big)<0 or abs(small)<0:
        print("정수를 입력해주세요")
    else:
        q = big//small
        r = big%small
        return(q,r)

#### 파이썬 베이직 229p
- 어떠한 string을 받으면 일정한 단위로 끊어서 화면에 출력하는 함수를 만들기
- 끊는 단위는 따로 정하지 않으면 2로 설정한다.

In [ ]:
def func(string, unit=2):
    i = 0
    while i < len(string):
        print(string[i:i+unit])
        i += unit

func("테스트를 위한 문장입니다")
func("테스트를 위한 문장입니다", 4)

- 가변함수 더 알아보기
- 참고 : https://mingrammer.com/understanding-the-asterisk-of-python/

## 전혀 모르겠군요.
#### 코드 다시한번 보기 - 떠오르지 않는다

#### 파이썬 베이직 230p
- add_all 함수 짜보기
- add_all(1,2,3,4,5,6,7,8,9,10)   ->답: 55
- 힌트) args 로 받은 후에 리스트로 다시 받아서 만들기

**이 밑 부분 다시 확인해보기(답비교확인해보기)**

In [ ]:
# 내가 따라 적은 해설

def add_all(*inputs):
    s = 0
    for i in range(len(inputs)):
        s += inputs[i]
    return s

add_all(1,2,3,4,5,6,7,8,9,10)   # 오류남. 리스트를 잘라서 쓸 수 없기 때문에 -> 되는데?



def add_all2(*inputs):
    return sum(inputs)



def add_all3(*args):        # 그래서 for문을 이중으로 돌림. 그러면 가능
    s = 0
    for i in args:
        for j in i:
            s += j
        return s

add_all3(1,2,3,4,5,6,7,8,9,10)




def add_all4(*args):
    temp = 0
    for i in range(len(args)):
        if type(args[i]) == list:
            for j in args[i]:
                temp += j
        else:
            temp += args[i]
    return temp
add_all4(1,2,3,4,5,6,7,8,9,10)


### 파이썬 베이직 239p
- 팩토리얼 구하기
- 1부터 시작해서 어떤 범위에 있는 모든 정수 곱하기

In [ ]:
#재귀적으로 하지 않은 것.
def fact(n):
    f=1 #곱을 계산할 변수의 초깃값
    for i in range(1,n+1): #1부터 n까지 반복
        f = f*i #곱셈연산
    return f

In [ ]:
#재귀적으로 하는 것.
def fact(n):
    if n<=1: #n이 1이하이면 종료조건
        return 1
    return n*fact(n-1)

fact(5)

참고 : https://velog.io/@joo4438/python-%ED%8C%A9%ED%86%A0%EB%A6%AC%EC%96%BC-%EA%B5%AC%ED%95%98%EA%B8%B0%EC%9E%AC%EA%B7%80

### enumerate(열거하다)
  - 반복 가능한 객체의 인덱스와 원소에 함께 접근 할 수 있는 함수.

In [ ]:
lst = ['a', 'b', 'c']
for x in enumerate(lst):
  print(x)

(0, 'a')
(1, 'b')
(2, 'c')


In [ ]:
lst1 = 'abcd'
for x in enumerate(lst1):
  print(x)

(0, 'a')
(1, 'b')
(2, 'c')
(3, 'd')


코로 다음과 같이 쓸 수 있다.

In [ ]:
people = ['펭수','뽀로로','뚝딱이','텔레토비']

def func1(line):
    new_lines = []
    for idx,val in enumerate(line):
        print('대기번호 %d번 : %s' %(idx,val))
        new_lines.append((idx+1,val))
    return new_lines

### zip()
- 반복가능한 객체들을(2개이상) 병렬적으로 묶어주는 함수
- 각 원소들을 튜플의 형식으로 묶어줌

### lambda
- 파이썬3에서는 사용권장되지 않으나
- 데이터분석에선 많이 쓰임.
- 단점 : 변수1개만 들어감
    - map함수를 이용하여 묶어줘야 함.

In [ ]:
func2 = lambda x : x+2
c = func2(2)
print(c)


In [ ]:
# map 함수 이용

items = [1,2,3,4,5]

squared_map = list(map(lambda x : x**2, items))
print(squared_map)




[1, 4, 9, 16, 25]


람다 연습문제 p.251
- 람다와 맵을 이용하여 items의 요소들을 string(문자)로 바꾸기

In [ ]:
items = [1,24,3,6,7]

str_items = list(map(lambda x:str(x),items))
print(str_items)

- 0~9까지를 순서대로 가지고 있는 리스트를 만들기

- 구구단 2단

In [ ]:
tables = [2*x for x in range(1,10)]
print(tables)

- 코로나 바이러스

In [ ]:
sentence = '코로나 바이러스를 예방하기 위해 사회적 거리두기를 실천합시다.'

len_sent = [len(s) for s in sentence.split()]
print(len_sent)

p.258
- for 문 + if 문
- 10부터 20까지 짝수만 담은 리스트를 만들어보기

In [ ]:
list3 = []
for x in range(10, 21):
  if x % 2 == 0:
    list3.append(x)
print(list3)


# 또는


lc_2 = [x for x in range(10,21) if x%2==0]
print(lc_2)

#### p.258
- 1부터 10의 제곱수 중 50 이하인 수만 리스트에 저장하기

In [ ]:

# 1부터 10의 제곱수 중 50 이하인 수만 리스트에 저장하기
lc_3 = [x**2 for x in range(1,11) if x**2<50]
print(lc_3)



# p. 258, 문2
sentence = '코로나 바이러스를 예방하기 위해 사회적 거리두기를 실천합시다.'
lc_4 = [s for s in sentence.split() if len(s)<5]

- 1부터 10까지의 숫자들 중 홀수이면 어떤 제곱수를, 짝수이면 세제곱수를 담은 리스트를 만들어보기

In [ ]:
list_4 = []
for x in range(1,11):
  if x%2==1:
    list_4.append(x**2)
  else:
    list_4.append(x**3)

# 또는(리스트 컴프리헨션)

[x**2 if x%2==0 else x**3 for x in range(1,11)]  # 리스트컴프리헨션은 조건 하나 늘어나면 무조건 앞으로 가야함.

- for문 + for문

In [ ]:
word1 = 'hello'
word2 = 'world'

result = [i+j for i in word1 for j in word2]      
result

#### 261p
1. 40 이하의 숫자는 5를 더하고 40 초과의 숫자는 41로 바꾸어 리스트로 저장하고 리스트를 출력하기
2. 컷트라인이 60점일때 사람이름과 통과여부를 리스트로 담아 출력하기. (이름과 통과여부는 튜플로 묶어있는 자료.)

In [ ]:
#1.
list_5 = [12,67,32,48,19,57,29,49]
lc_6 = [x+5 if x<=40 else 41 for x in list_5]
lc_6

#2
students = {"보라돌이":61, "뚜비":35, "나나":78, "뽀":88}

result = [(name,True) if score>60 else(name,False) for name,score in students.items()]
result

[('보라돌이', True), ('뚜비', False), ('나나', True), ('뽀', True)]

####Ndarray vs list

In [ ]:
# 코렙에서 돌릴때

import numpy as np

n=1000000
numpy_arr = np.arange(n)
python_list = list(range(n))



In [ ]:
# vs코드에서 돌릴때

import time
start = time.time() #시작시간 저장
python_list = [x**3+10 for x in python_list]
print('time:', time.time() - start) #현재시각-시작시간 = 실행시간

- 정수부는 초단위, 소수부는 마이크로 초단위 입니다.

In [ ]:
%%time
numpy_arr = numpy_arr**3+10

CPU times: user 5.9 ms, sys: 4.51 ms, total: 10.4 ms
Wall time: 44.1 ms


#### 벡터화
- 배열은 for문을 작성하지 않고 데이터를 일괄처리 하는것

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr
arr+arr
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

#### 브로드캐스팅
- 다른 모양의 배열 간 산술연산을 수행할 수 있도록 해주는 numpy의 기능
- 아래와 같은 연산을 지원함.

In [ ]:
10-arr

array([[9, 8, 7],
       [6, 5, 4]])

In [ ]:
arr/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [ ]:
arr*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
# 참고) 1열로 쓰고싶을때 (위의 행렬은 행으로 쓴거임)
arr4 = np.array([100],
                [200])

- 하지만 다음은 안됨.

In [ ]:
# arr2 = np.array([100,200,300])
# arr3 = np.array([100,200])
# arr2 + arr3

ValueError: ignored

- 리스트와 비교

In [ ]:
# 리스트
li_1 = [1,2,3]
li_1 + li_1

[1, 2, 3, 1, 2, 3]

In [ ]:
# Numpy
arr_1 = np.array([1,2,3])
arr_1 + arr_1

array([2, 4, 6])

#### dtype
- 배열에 담긴 원소의 자료형



#### size
- 배열에 있는 원소의 전체 갯수

#### ndim
- 배열의 차원의 갯수
- shape을 더 많이 쓰기는 함.

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(3,)

- 0차원 : 상수

In [ ]:
import numpy as np
# a = np.array(10)
# print(a)
# print(a.ndim)

10
0


- 1차원

In [ ]:
import numpy as np
# a = np.array([1,2,3])
# print(a)
# print(a.ndim)

[1 2 3]
1


- 2차원

In [ ]:
# a = np.array([[1,2],[3,4]])
# print(a)
# print(a.ndim)

[[1 2]
 [3 4]]
2


#### 3차원
여기서부터 복잡해짐
- 그래서 데이터분석할때는 3D 안함. 2D로 내려와서 작업.

In [ ]:
# a = np.array([[[1,2],[3,4]]])
# print(a)
# print(a.ndim)
# print(a.shape)   #-> 이게 이상해짐.

[[[1 2]
  [3 4]]]
3
(1, 2, 2)


- range 함수를 이용

In [ ]:
arr1 = np.array(range(20))
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# 위와 같은 결과. 같은데 다른방식으로 표현. 이 표현을 많이 씀
arr2 = np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

- (참고) 간단하게 쓸 수도 있으나 코딩테스트를 볼 때에 패키지를 못쓸 때가 있음. 그래서 패키지 안쓰고 코딩 하는 법을 알아야함.

#### 배열 생성 함수
- zeros : np.zeros(5) -> 0이 할당된 것
- ones : np.ones((3,3))
- full : np.full((4),5)
- empty : np.empty((2,3),dtype=np.float64) -> 0이 할당 안됌
- (참고) none : 
- arange : 
-linspace : 잘게 쪼갤때 -> linspace(0,1,6) : 0부터 1까지 6개로 쪼개달라

#### 배열 결합 함수
- hstack, concatenate
- 두 배열을 왼쪽에서 오른쪽으로 붙이기
- 단점 : 2차원일때 조금 이상하게 붙음.

In [ ]:
# a = np.array([1,2,3])
# b = np.array([4,5,6])

# # np.hstack([a,b])
# np.concatenate((a,b),axis=0)    # axis=0 은 행을 인식함

array([1, 2, 3, 4, 5, 6])

In [ ]:
# a = np.array([[1,2],[3,4]])
# b = np.array([[5,6],[7,8]])

# np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

- vstack(vertical), concatenate(axis=1)

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# np.vstack([a,b])

# np.concatenate((a,b),axis=1) #->이건 안됨. 1D vector는 안됨.

In [ ]:
# c = np.array([[0,1,2],[3,4,5]])
# d = np.array([[6,7,8],[9,10,11]])

# np.concatenate((c,d),axis=1)  #-> 이렇게는 됨.

- 두 배열을 위 아래로 붙이기

In [ ]:
a,b

In [ ]:
np.column_stack([a,b])

- 랜덤 모듈

In [ ]:
import random
import numpy as np

random.random() #<=리턴값<=1

0.7077719831686492

In [ ]:
data = [1,2,3,4,5,6,7]

np.random.choice(data,3)

array([6, 5, 5])

In [ ]:
data = ['apple','banana','grape','orange']

random.choice(data)

'orange'

- seed : 난수 초기값 부여. -> 재현가능성 높이기 위해 
내가 보낸 코드가 남에게도 똑같이 돌아가게 하기 위해

In [ ]:
np.random.seed(42) # 42번 동안 난수 똑같이 유지해라

In [ ]:
np.random.rand(1000)

In [ ]:
np.random.randn(1000) #정규분포

- 강의자료) 파이썬 넘피) p.43
- 로또번호 생성기 만들기

In [ ]:
import numpy as np
def make_lotto(count):
    for i in range(count):
        lotto_num = [] #로또 번호가 담길 리스트형 변수
        for j in range(6): #6번 반복
            lotto_num = np.random.choice(range(1,46),6,replace=False)
            lotto_num.sort() #값 정렬
        print('{}.로또번호:{}'.format(i+1,lotto_num))

- (range(1,46),6 : 45개 중에 6개 뽑아달라
- replace=False  : 중복추출 막음.

In [ ]:
count = int(input('로또 번호를 몇개 생성할까요?'))
make_lotto(count)

로또 번호를 몇개 생성할까요?3
1.로또번호:[18 22 24 28 35 36]
2.로또번호:[17 26 30 32 33 44]
3.로또번호:[ 3 12 13 27 30 37]
