<a href="https://colab.research.google.com/github/HYEEYH/my_study/blob/main/20230503_20230504.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 파이썬 심화 복습
### args
#### python basic p.230
- 문) add_all 함수 만들어보기
- add_all(1,2,3,4,5,6,7,8,9,10)
- (힌트) *args를 input으로 받기

In [ ]:
def add_all(*inputs):             # 튜플을 한번만 가져와서 쓰는것은 가능. 수정하는게 아니라서
    a = 0
    for i in range(len(inputs)):
        a += inputs[i]
    return a

print(add_all(1,2,3,4,5,6,7,8,9,10))

55


In [ ]:
# 오류남.튜플은 수정할 수 없기때문에 가져와서 또 뭔가를 하려고 하면 안됌.
# for문을 이중으로 돌리면 불가. 튜플에서 뽑아와서 무언가를 하는것이기 때문.
def add_all3(*args):        
    s = 0 
    for i in args:
        for j in i:
            s += j
        return s

add_all3(1,2,3,4,5,6,7,8,9,10)

TypeError: ignored

In [ ]:
# 오류가 나지 않게 하는 방법.

def add_all4(*args):
    temp = 0
    for i in range(len(args)):
        if type(args[i]) == list:
            for j in args[i]:
                temp += j
        else:
            temp += args[i]
    return temp
add_all4(1,2,3,4,5,6,7,8,9,10)

55

## Numpy 복습
- 어레이 안에 있는 각각이 전부 객체(object)가 된다
- 리스트보다 집어 넣는것은 느리지만 꺼내 쓰는것은 빠름.(각각 따로 쓸 수 있어서)


#### array 실습

In [ ]:
import numpy as np
A = [1,2,3,4]
a = np.array(A)
s = a[:2]
print('A의 출력입니다. %a' %a)
print("s의 출력입니다. %s" %s)

A의 출력입니다. array([1, 2, 3, 4])
s의 출력입니다. [1 2]


In [ ]:
type(A)

list

In [ ]:
a1 = np.asarray(A)
print(type(a1))
a1

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

- Ndarray 타입을 검색하거나 슬라이싱은 참조만 할당하므로(값만 전달됨) 변경을 방지하기 위하서는 새로운 ndarray로 만들어 사용. copy메소드가 필요
- 

In [ ]:
ss = a[:2].copy()
print(ss.size)
ss[0] = 99
print(a)
print(s)
print(ss)

2
[1 2 3 4]
[1 2]
[99  2]


#### 벡터화
- 배열은 for문을 작성하지 않고 데이터를 일괄처리 하는것

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

#### 브로드캐스팅

## 복습 끝.

## 플래튼

In [ ]:
arr = np.zeros((3,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
arr.flatten()  #1D vector로 만드는것

In [ ]:
arr = np.array([[1,2],[3,4]])
arr.flatten()

np.array([1,2,3,4])    # 오류 왜 나는거지??

array([1, 2, 3, 4])

## reshape
- 이미 존재하는 배열을 내가 원하는대로 shape을 조정함

In [ ]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- <주의사항>주어진 shape의 약수로 이루어진 shape만 가능

In [ ]:
# arr.reshape(4,3)
# arr.reshape(1,12)    #-> 이건 flatten()을 썼을때와 같은 결과 나옴.
# arr.reshape(12,1)
# arr.reshape(2,6)
# arr.reshape(6,2)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
arr = np.arange(20)

arr.reshape(4,5)
# arr.reshape(-1,5)            # 이런식으로 하나를 축으로 정해서 -를 붙이면 자동으로 약수로 돌아감
# arr.reshape(5,-1)            # 주의사항) 축을 정해줘야함. 둘 다 - 붙이면 안됨.
                             # arr.reshape(10,-1)  또는   arr.reshape(-1,2)  도 ok. (-> 축을 정했다면 ㅇㅋ)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
# arr = np.arange(20).reshape(4,5)           # 이렇게 바로 붙여서 써도 상관없음.

## 트랜스포즈
- 행과 열을 바꿈
- 리턴함수가 없어서 원래 모양에서 안바뀌니까 선언(?)해줘야함
- 근데 잘 안씀.
- 축을 건드릴 수는 있으나 3차원부터는 안쓰는게 좋음

- -> T operation을 주로 씀

In [ ]:
print(arr.transpose().shape)
arr.transpose()                 
# 리턴함수가 없어서 원래 모양에서 안바뀜
# 선언(?)해줘야 함   

(20,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr1 = np.arange(4).reshape(-1,2)
arr1

array([[0, 1],
       [2, 3]])

In [ ]:
arr1.transpose()

array([[0, 2],
       [1, 3]])

In [ ]:
# 트랜스포즈의 단점

arr = np.arange(30).reshape(3,2,5)
arr.shape

(3, 2, 5)

In [ ]:
arr.transpose().shape   # -> 차원이 바뀜. 축을 건드릴 수 있긴 하나. 3차원부터는 안쓰는것이 좋다.

(5, 2, 3)

In [ ]:
# (참고)
# sort 와 sorted

# sort -> 리턴함수가 있음. 그래서 출력하면 모양이 바뀜
a = [5,23,2,1,5]
a.sort()
print(a)

[1, 2, 5, 5, 23]


In [ ]:
# sorted -> 리턴함수가 없음. 고로 출력해도 안바뀜
a1 = [5,23,2,1,5]
sorted(a1)
print(a1)


[5, 23, 2, 1, 5]


### T operation

In [ ]:
arr.T

x = np.arange(6).reshape(-1,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

#### <강의자료> Numpy p.54
- 문제2) 0~20까지 숫자의 배열을 만든 다음 arr1에는 짝수, 
arr2는 홀수가 들어간 배열을 출력해보기

In [ ]:
import numpy as np

arr = np.arange(0,21)
arr1 = []
arr2 = []
for i in arr:
  if arr[i] % 2 == 0:
    arr1.append(arr[i])
  else:
    arr2.append(arr[i])

print(arr1)
print(arr2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [ ]:
# 위의 코드와 동일한 코드

import numpy as np
Arr = np.arange(0,21)

Arr1 = Arr[Arr%2==0]
Arr2 = Arr[Arr%2!=0]

print(Arr)
print(Arr1)
print(Arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]
[ 1  3  5  7  9 11 13 15 17 19]


- 슬라이싱 가능


In [ ]:
arr1d = np.arange(8)

# arr1d[1]
# arr1d[-1]
arr1d[:4]

array([0, 1, 2, 3])

- 브로드캐스팅 해보기

In [ ]:
# 리스트에 연산해보기
lst = list(range(6))
print(lst)



[0, 1, 2, 3, 4, 5]


In [ ]:
lst[2:5] = -1
print(lst)             # 불가. 오류남

TypeError: ignored

In [ ]:
lst[3] = -1
print(lst)

[0, 1, 2, -1, 4, 5]


- 넘피에서는 브로드캐스팅 가능

In [ ]:
arr1c = np.arange(8)
arr1c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr1c[3:6]=100
arr1c

array([  0,   1,   2, 100, 100, 100,   6,   7])

- view

In [ ]:
arr2d = np.arange(20).reshape(4,-1)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr2d[0]  #첫번째 행 나옴

array([0, 1, 2, 3, 4])

In [ ]:
arr2d[1][2] # 재귀적 접근/ 1행 2열 나옴

7

In [ ]:
arr2d[1,2] # ,를 이용하여 쉽게 인덱싱 할 수 있음. 1행2열

7

In [ ]:
arr2d[:3,:2]  # 행과 열에 접근하기 위해서는 컴마로 연결해야함. -> 행 열이 많은데 그 중 1~3행,1~2열 까지만 나오게 할때.

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

- 불리안 배열

In [ ]:
arr_1 = np.array([0,1,2,3,4])
arr_1[[True,False,True,False,True]]   #True인것만 나옴

array([0, 2, 4])

- 정수 배열을 사용한 인덱싱
- 

In [ ]:
arr_2 = np.arange(20).reshape(4,5)
arr_2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
# 0행과 2행
# multi index는 []를 하나 더 추가해야함.

arr_2[[0,2]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [ ]:
# 0행과 3행의 4번째자리만 가져오기
arr_2[[0,3],[4]]

array([ 4, 19])

In [ ]:
# 0행과 1행의 4번째, 3번째 자리만 가져오기 ++++++++++++++++ 0,3 하면 숫자 이상...?
arr_2[[0,1],[4,3]]

array([ 4, 18])

### 유니버셜 함수

In [ ]:
arr_4 = np.arange(-3,3).reshape(3,-1)
arr_4

array([[-3, -2],
       [-1,  0],
       [ 1,  2]])

- 각 원소의 e^x승 계산(e의 x승)

In [ ]:
np.exp(arr)

- floor : 소수점 버리기

In [ ]:
np.floor(arr)

- 이항 유니버셜 함수

In [ ]:
arr1 = np.arange(8).reshape(2,-1)
arr2 = np.arange(-40,40,10).reshape(2,-1)
print(arr1)
print(arr2)

[[0 1 2 3]
 [4 5 6 7]]
[[-40 -30 -20 -10]
 [  0  10  20  30]]


In [ ]:
# 같은 원소에서 가장 큰 값을 알려줌   ++++++++++++++이해 안감 + 아 OK
np.maximum(arr1,arr2)

array([[ 0,  1,  2,  3],
       [ 4, 10, 20, 30]])

In [ ]:
# 뺄셈
np.subtract(arr1,arr2)

array([[ 40,  31,  22,  13],
       [  4,  -5, -14, -23]])

In [ ]:
# 곱셈
np.multiply(arr1,arr2)

array([[  0, -30, -40, -30],
       [  0,  50, 120, 210]])

#### 통계 메소드
- 축을 건드릴 수 있음.

In [ ]:
arr_5 = np.arange(4).reshape(2,2)
arr_5

array([[0, 1],
       [2, 3]])

In [ ]:
arr_5.sum()

6

In [ ]:
arr_5.sum(axis=0)   # 열로 접근해서 더함. 1열끼리 더하고 2열끼리 더하고

array([2, 4])

In [ ]:
arr_5.sum(axis=1)   # 행으로 접근해서 더함. 1행끼리 더하고 2행끼리 더하고

array([1, 5])

In [ ]:
arr_5.mean()  # 평균

1.5

In [ ]:
arr_5.mean(axis=0)  # 열 평균
# 근데 답이 왜 소수점으로 나올까
# 수 체계때문에. 정수보다 소수로 표현하는게 더 큰 범위의 표현. (실수- 유리수(분수)- 정수 순)
# 나누기를 해서 나오는 답을 분수로 표현하는게 더 안전

array([1., 2.])

In [ ]:
arr_5.mean(axis=1)  # 행 평균

array([0.5, 2.5])

### 기타 메소드

- where
  - x if 조건 else y의 벡터화 버전
  - numpy를 사용하여 배열을 빠르게 처리할 수 있으며 다차원도 간결하게 표현이 가능.

In [ ]:
xarr = np.array([100,200,300,400])
yarr = np.array([1,2,3,4])
cond = np.array([True,False,True,False])

In [ ]:
result = np.where(cond,xarr,yarr)
result

# 출력
# result = np.where(cond,xarr,yarr) 의
# xarr : true
# yarr : false
# array([100,   2, 300,   4])
#       xarr, yarr, x,    y

array([100,   2, 300,   4])

In [ ]:
np.where(xarr>200,max(xarr),0)

array([  0,   0, 400, 400])

In [ ]:
np.where(xarr%3==0,1,0)

array([0, 0, 1, 0])

- sort()
  - array의 sort에서는 내림차순, 오름차순을 선택하는 옵션이 없다.(->리스트의 sort와 다른점)

In [ ]:
np.random.seed(42)
arr = np.random.randint(1,100,size=10)  #1~100까지의 정수 중 10개를 뽑아달라
arr

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

In [ ]:
arr.sort()
arr

array([15, 21, 52, 61, 72, 75, 75, 83, 87, 93])

In [ ]:
# 뒤집고 싶으면 -를 잘 써야함.(위치 확인)

In [ ]:
-np.sort(-arr)  #리버스 옵션이 없음. 부호를 이용하여 내림차순으로 정렬
# 리스트 sort 에는 리버스 옵션이 있으나 어레이의 sort는 리버스 옵션 없음.

array([93, 87, 83, 75, 75, 72, 61, 52, 21, 15])

### 선형대수 패키지 
- 단위행렬
  - 대각원소가 1이고 나머지는 0인 n차 정방행렬을 말함
  - numpy의 eye()함수를 사용하여 만들 수 있다

In [ ]:
# 사용방법
import numpy as np
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
identity1 = np.eye(2,3)
print(identity1)

[[1. 0. 0.]
 [0. 1. 0.]]


- 대각행렬
  - 대각 성분 이외의 모든 성분이 모두 0인 n차 정방행렬

In [ ]:
x = np.arange(9).reshape(3,-1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
np.diag(x)  # diagonal matrix 라고 함

array([0, 4, 8])

In [ ]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

- dot
  - 원소간의 곱(element-wise product)
  - 벡터의 내적(행렬의 곱) 곱해서 더하는걸 내적이라고 함.

In [ ]:
a = np.arange(4).reshape(-1,2)
print(a)

[[0 1]
 [2 3]]


In [ ]:
a*a  #dot product

array([[0, 1],
       [4, 9]])

In [ ]:
np.multiply(a,a)

array([[0, 1],
       [4, 9]])

In [ ]:
np.dot(a,a)  # 행렬의 곱

# 또는

# a.dot(a)    # 행렬의 곱. 위와 같은 코드

array([[ 2,  3],
       [ 6, 11]])

- matmul : matrix multiplication

In [ ]:
a = np.random.randint(-3,3,10).reshape(2,5)
b = np.random.randint(0,5,15).reshape(5,3)
a.shape,b.shape

((2, 5), (5, 3))

In [ ]:
# a와 b를 곱한다
ab = np.matmul(a,b)
print(ab.shape,"\n")   #\n ; 개행
print(ab)

(2, 3) 

[[  7  11   4]
 [ -2 -10  -2]]


In [ ]:
ba = np.matmul(b,a)   
#오류남. 곱하려는 행 렬 수가 안맞음. shape이 안맞으면 reshape등을 통해 모양을 서로 맞춰준 뒤 곱해야 함.

ValueError: ignored

In [ ]:
np.dot(a,b)
# 이거는 오류 안남. 왜냐하면
# dot -> 1차원 벡터. 공식문서에는 2차원 matmul로 돌아감.

# pandas

In [ ]:
# 설치를 원할경우

#!pip install numpy  # 느낌표를 쓴 이유는 리눅스에서는 이렇게 해야 돌아가는데 코렙은 리눅스
#!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
# 내가 쓴거
obj = pd.Series([0,1,2,3,4,5,6,7], index=["a","b","c","d","e","f","g","h"], dtype="int64")
obj

In [ ]:
# 복사해온거
obj = pd.Series([0,1,2,3,4,5,6,7], index=['a','b','c','d','e','f','g','h'],
                                          dtype='int64')
obj

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

- integer-location based
  - 정수 기반. 순서에 따라 가져오는 방법들

In [ ]:
# 슬라이싱 가능
obj[3]

In [ ]:
obj[-1]

In [ ]:
# 멀티인덱스 접근 방법
obj[[1,3,5]] 

In [ ]:
# 순서가 있게끔 가져오고 싶으면
obj[1:3]  # 첫번째~ 세번쨰

In [ ]:
# 조건을 가지고 가져오고싶을때
obj[obj<3]  # boolean indexing

a    0
b    1
c    2
dtype: int64

In [ ]:
obj<3

a     True
b     True
c     True
d    False
e    False
f    False
g    False
h    False
dtype: bool

- label location based

In [ ]:
obj

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

In [ ]:
obj.c   # 이렇게 접근하는것도 가능

2

In [ ]:
obj['c']

2

In [ ]:
obj[['e','c']]  # 멀티 인덱스 접근

e    4
c    2
dtype: int64

In [ ]:
obj['a':'d']  # a ~ d까지

a    0
b    1
c    2
d    3
dtype: int64

In [ ]:
obj['d':'e'] = 100   
# 이건 될까??
# 되는 이유 - 넘피 위에서 돌기때문에. 넘피의 브로드캐스팅. 판다스도 브로드캐스팅 됨.
obj

a      0
b      1
c      2
d    100
e    100
f      5
g      6
h      7
dtype: int64

- integer location based(iloc)

In [ ]:
obj = pd.Series([0,1,2,3,4,5,6,7], index=["a","b","c","d","e","f","g","h"], dtype="int64")
obj

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

In [ ]:
obj.iloc[2]

2

In [ ]:
obj.iloc[[2]]   #멀티인덱스로 감싸면 라벨이랑 값이 둘 다 나옴

c    2
dtype: int64

In [ ]:
obj.iloc[1:4]

b    1
c    2
d    3
dtype: int64

- location based

In [ ]:
obj.loc['a':'c']
# loc은 라벨로 접근하는거
# iloc은 integer로 접근하는거임

# 결과는 같아 보이지만 암튼 뭔가 다름. 데이터 분석할떄 달라짐.

a    0
b    1
c    2
dtype: int64

In [ ]:
# 데이터프레임
import numpy as np
df = pd.DataFrame(np.arange(24).reshape(4,-1), columns = ['c1','c2','c3','c4','c5','c6'], index=['r1','r2','r3','r4'])
df

c1  c2  c3  c4  c5  c6
r1   0   1   2   3   4   5
r2   6   7   8   9  10  11
r3  12  13  14  15  16  17
r4  18  19  20  21  22  23

In [ ]:
df['c3']  # df의 c3은 뭐니?

# 또는

#df.c3

r1     2
r2     8
r3    14
r4    20
Name: c3, dtype: int64

In [ ]:
df[c1,c3]  # 이렇게 쓰면 오류남

NameError: ignored

In [ ]:
df[['c1','c3']]  # 멀티인덱스를 써야 오류 안남

c1  c3
r1   0   2
r2   6   8
r3  12  14
r4  18  20

In [ ]:
df['r1':'r2']   # r1에서 r2까지 가져와라

c1  c2  c3  c4  c5  c6
r1   0   1   2   3   4   5
r2   6   7   8   9  10  11

In [ ]:
df['c1':'c2']   # 이건 왜 값이 안나올까??

# -> 컴퓨터는 열 중심으로 읽음
# r1에서 r2로 갈때는 데이터가 안끊김.(위에서부터 열을 따라가면서 내려다보면서 읽을때)
# (0.1.2.3.4.5.6.7.8.9.0.11)까지 전부 읽을 수 있음.
# 그런데!
# c1에서 c2로 갈때 데이터가 중간에 끊김 (위에서부터 열을 따라가며 내려다보며 읽을때 )
# (0,6,12,18 읽고 그 뒤에 아무것도 없어서 못읽음. c2 처음으로 다시 못올라감)

# 그리고 멀티 인덱스 써야함

Empty DataFrame
Columns: [c1, c2, c3, c4, c5, c6]
Index: []

In [ ]:
df[['c1','c2']]

c1  c2
r1   0   1
r2   6   7
r3  12  13
r4  18  19

- iloc
정수 로케이션

In [ ]:
df.iloc[[0],[3]]

c4
r1   3

In [ ]:
df.iloc[[0,1],1:4]

c2  c3  c4
r1   1   2   3
r2   7   8   9

- loc
라벨로케이션

In [ ]:
df.loc[['r1'],['c4']]

c4
r1   3

In [ ]:
df.loc['r1':'r2', ['c2','c3','c4']]

c2  c3  c4
r1   1   2   3
r2   7   8   9

In [ ]:
df.loc['r1':'r2', ['c3','c4','c2']]

c3  c4  c2
r1   2   3   1
r2   8   9   7

- 산술연산자

In [ ]:
s1 = pd.Series([1,2,3,4], index=['a','b','c','d'])
s2 = pd.Series([10,20,30,40], index=['a','b','c','d'])
s1 + s2

a    11
b    22
c    33
d    44
dtype: int64

In [ ]:
s1 = pd.Series([1,2,3,4], index=['a','b','c','d'])
s2 = pd.Series([10,20,30,40], index=['b','c','d','e'])
s1 + s2  # SQL의 Outer Join

# NaN(Not a Number) : 숫자가 없다.
# 인덱스는 고유영역
# 영역이 겹치는 교집합만 나옴. 
# a,e는 값이 없으니까 호출이 안됨.

a     NaN
b    12.0
c    23.0
d    34.0
e     NaN
dtype: float64

In [ ]:
s1.add(s2,fill_value=0)  # 합칠때 빈 값은 0으로 채워달라

a     1.0
b    12.0
c    23.0
d    34.0
e    40.0
dtype: float64

In [ ]:
s2.add(s1,fill_value=0)

a     1.0
b    12.0
c    23.0
d    34.0
e    40.0
dtype: float64

강사님 깃허브 - 렉쳐노트 - 파이썬 - stock_2020_01.csv - Raw - 열리면 주소 복사해서 붙여넣기

- vs코드에서는 안됨

In [ ]:
import pandas as pd

stock = pd.read_csv('https://raw.githubusercontent.com/Youngpyoryu/Lecture_Note/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC/stock_2020_01.csv', encoding= 'CP949')
stock

Date    kospi  kosdaq  gold_fut_132030  Bond_273130
0    2020. 1. 2 오후 3:30:00  2175.17  674.02            10845       108215
1    2020. 1. 3 오후 3:30:00  2176.46  669.93            11000       108565
2    2020. 1. 6 오후 3:30:00  2155.07  655.31            11245       108745
3    2020. 1. 7 오후 3:30:00  2175.54  663.44            11180       108400
4    2020. 1. 8 오후 3:30:00  2151.31  640.94            11360       108270
5    2020. 1. 9 오후 3:30:00  2186.45  666.09            11055       107980
6   2020. 1. 10 오후 3:30:00  2206.39  673.03            11035       107760
7   2020. 1. 13 오후 3:30:00  2229.26  679.22            11080       107695
8   2020. 1. 14 오후 3:30:00  2238.88  678.71            10975       107860
9   2020. 1. 15 오후 3:30:00  2230.98  679.16            11060       108020
10  2020. 1. 16 오후 3:30:00  2248.05  686.52            11060       108015
11  2020. 1. 17 오후 3:30:00  2250.57  688.41            11075       107830
12  2020. 1. 20 오후 3:30:00  2262.64  683.47            11140       107775
13  2020. 1. 21 오후 3:30:00  2239.69  676.52            11155       108040
14  2020. 1. 22 오후 3:30:00  2267.25  688.25            11050       107995
15  2020. 1. 23 오후 3:30:00  2246.13  685.57            11080       107970
16  2020. 1. 28 오후 3:30:00  2176.72  664.70            11250       108450
17  2020. 1. 29 오후 3:30:00  2185.28  670.18            11160       108585
18  2020. 1. 30 오후 3:30:00  2148.00  656.39            11225       108810
19  2020. 1. 31 오후 3:30:00  2119.01  642.48            11210       108795

In [ ]:
# Raw - 열리면 빈 부분에 마우스 오른쪽버튼 - 다른이름으로 저장
# 코렙 왼쪽 파일모양 아이콘 - 파일 열기 - 연 파일 오른쪽버튼 - 경로에서 주소 복사 - 인코딩 앞 '' 안에 주소 넣기

import pandas as pd
stock = pd.read_csv('/content/stock_2020_01.csv',encoding='CP949')
stock

Date    kospi  kosdaq  gold_fut_132030  Bond_273130
0    2020. 1. 2 오후 3:30:00  2175.17  674.02            10845       108215
1    2020. 1. 3 오후 3:30:00  2176.46  669.93            11000       108565
2    2020. 1. 6 오후 3:30:00  2155.07  655.31            11245       108745
3    2020. 1. 7 오후 3:30:00  2175.54  663.44            11180       108400
4    2020. 1. 8 오후 3:30:00  2151.31  640.94            11360       108270
5    2020. 1. 9 오후 3:30:00  2186.45  666.09            11055       107980
6   2020. 1. 10 오후 3:30:00  2206.39  673.03            11035       107760
7   2020. 1. 13 오후 3:30:00  2229.26  679.22            11080       107695
8   2020. 1. 14 오후 3:30:00  2238.88  678.71            10975       107860
9   2020. 1. 15 오후 3:30:00  2230.98  679.16            11060       108020
10  2020. 1. 16 오후 3:30:00  2248.05  686.52            11060       108015
11  2020. 1. 17 오후 3:30:00  2250.57  688.41            11075       107830
12  2020. 1. 20 오후 3:30:00  2262.64  683.47            11140       107775
13  2020. 1. 21 오후 3:30:00  2239.69  676.52            11155       108040
14  2020. 1. 22 오후 3:30:00  2267.25  688.25            11050       107995
15  2020. 1. 23 오후 3:30:00  2246.13  685.57            11080       107970
16  2020. 1. 28 오후 3:30:00  2176.72  664.70            11250       108450
17  2020. 1. 29 오후 3:30:00  2185.28  670.18            11160       108585
18  2020. 1. 30 오후 3:30:00  2148.00  656.39            11225       108810
19  2020. 1. 31 오후 3:30:00  2119.01  642.48            11210       108795

In [3]:
# 구글 드라이브에 파일 넣어두고 마운트 해서 가져오는게 일반적인 방법

# from google.colab import drive
# drive.mount('/content/drive')

# 코렙 왼쪽 구글드라이브모양 파일 아이콘 - 파일 열기 - 연 파일 오른쪽버튼 - 경로에서 주소 복사 
# - 인코딩 앞 '' 안에 주소 넣기
import pandas as pd
stock = pd.read_csv('/content/drive/MyDrive/stock_2020_01.csv',encoding='CP949')
stock

Date    kospi  kosdaq  gold_fut_132030  Bond_273130
0    2020. 1. 2 오후 3:30:00  2175.17  674.02            10845       108215
1    2020. 1. 3 오후 3:30:00  2176.46  669.93            11000       108565
2    2020. 1. 6 오후 3:30:00  2155.07  655.31            11245       108745
3    2020. 1. 7 오후 3:30:00  2175.54  663.44            11180       108400
4    2020. 1. 8 오후 3:30:00  2151.31  640.94            11360       108270
5    2020. 1. 9 오후 3:30:00  2186.45  666.09            11055       107980
6   2020. 1. 10 오후 3:30:00  2206.39  673.03            11035       107760
7   2020. 1. 13 오후 3:30:00  2229.26  679.22            11080       107695
8   2020. 1. 14 오후 3:30:00  2238.88  678.71            10975       107860
9   2020. 1. 15 오후 3:30:00  2230.98  679.16            11060       108020
10  2020. 1. 16 오후 3:30:00  2248.05  686.52            11060       108015
11  2020. 1. 17 오후 3:30:00  2250.57  688.41            11075       107830
12  2020. 1. 20 오후 3:30:00  2262.64  683.47            11140       107775
13  2020. 1. 21 오후 3:30:00  2239.69  676.52            11155       108040
14  2020. 1. 22 오후 3:30:00  2267.25  688.25            11050       107995
15  2020. 1. 23 오후 3:30:00  2246.13  685.57            11080       107970
16  2020. 1. 28 오후 3:30:00  2176.72  664.70            11250       108450
17  2020. 1. 29 오후 3:30:00  2185.28  670.18            11160       108585
18  2020. 1. 30 오후 3:30:00  2148.00  656.39            11225       108810
19  2020. 1. 31 오후 3:30:00  2119.01  642.48            11210       108795

In [ ]:
stock.head() # 위에서 5개 읽기
# 5개 아니고 개수 다르게 읽고싶으면 ()안에 숫자 넣기

Date    kospi  kosdaq  gold_fut_132030  Bond_273130
0  2020. 1. 2 오후 3:30:00  2175.17  674.02            10845       108215
1  2020. 1. 3 오후 3:30:00  2176.46  669.93            11000       108565
2  2020. 1. 6 오후 3:30:00  2155.07  655.31            11245       108745
3  2020. 1. 7 오후 3:30:00  2175.54  663.44            11180       108400
4  2020. 1. 8 오후 3:30:00  2151.31  640.94            11360       108270

In [ ]:
stock.tail()  # 밑에서 5개 읽기

Date    kospi  kosdaq  gold_fut_132030  Bond_273130
15  2020. 1. 23 오후 3:30:00  2246.13  685.57            11080       107970
16  2020. 1. 28 오후 3:30:00  2176.72  664.70            11250       108450
17  2020. 1. 29 오후 3:30:00  2185.28  670.18            11160       108585
18  2020. 1. 30 오후 3:30:00  2148.00  656.39            11225       108810
19  2020. 1. 31 오후 3:30:00  2119.01  642.48            11210       108795

- 기술통계량

In [ ]:
stock.describe()

kospi      kosdaq  gold_fut_132030  Bond_273130
count    20.00000   20.000000        20.000000      20.0000
mean   2203.44250  671.117000     11112.000000  108188.7500
std      43.83648   14.040831       115.762916     364.6912
min    2119.01000  640.940000     10845.000000  107695.0000
25%    2175.44750  664.385000     11053.750000  107942.5000
50%    2196.42000  673.525000     11080.000000  108030.0000
75%    2241.30000  680.282500     11187.500000  108478.7500
max    2267.25000  688.410000     11360.000000  108810.0000

위에서부터
- 개수
- 평균
- 표준편차
- 최소값
- 데이터의 25%값
- 데이터의 50%값(중앙값) median = 50%
- 데이터의 75%값
- 최대값

**수치형** 자료만 나옴(숫자 **만** 있어야 함) 

(참고) 평균과 중앙값의 차이

In [ ]:
A = np.array([16,12,28,8,18,17,28,24,5,4,12,16,8,4,4,4])

In [ ]:
sorted(A)

[4, 4, 4, 4, 5, 8, 8, 12, 12, 16, 16, 17, 18, 24, 28, 28]

In [ ]:
np.mean(A)  # 평균

13.0

In [ ]:
np.median(A)  # 중앙값

12.0

- 결측치 확인(missing value)

In [ ]:
# 결측치 있나 확인하는 방법
stock.isna()

Date  kospi  kosdaq  gold_fut_132030  Bond_273130
0   False  False   False            False        False
1   False  False   False            False        False
2   False  False   False            False        False
3   False  False   False            False        False
4   False  False   False            False        False
5   False  False   False            False        False
6   False  False   False            False        False
7   False  False   False            False        False
8   False  False   False            False        False
9   False  False   False            False        False
10  False  False   False            False        False
11  False  False   False            False        False
12  False  False   False            False        False
13  False  False   False            False        False
14  False  False   False            False        False
15  False  False   False            False        False
16  False  False   False            False        False
17  False  False   False            False        False
18  False  False   False            False        False
19  False  False   False            False        False

In [ ]:
stock.isna().sum()  # 더해서 확인하는게 더 편함
# 이거는 결측치 없음.
# 또는
#stock.isnull.sum()


## 주의 () 빼먹으면 컴퓨터 상으로 연산은 하지만 출력은 안함.
## 아까 sort도 마찬가지. ()빼면 함수만 호출했지 적용을 안한거임.

Date               0
kospi              0
kosdaq             0
gold_fut_132030    0
Bond_273130        0
dtype: int64

- 데이터의 자료형이 뭔지 궁금할때
  - info()

In [ ]:
stock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Date             20 non-null     object 
 1   kospi            20 non-null     float64
 2   kosdaq           20 non-null     float64
 3   gold_fut_132030  20 non-null     int64  
 4   Bond_273130      20 non-null     int64  
dtypes: float64(2), int64(2), object(1)
memory usage: 928.0+ bytes


In [ ]:
stock['Date']
# 3:30에 끝나는 이유는 주식 장 마감시간이라서.

0      2020. 1. 2 오후 3:30:00
1      2020. 1. 3 오후 3:30:00
2      2020. 1. 6 오후 3:30:00
3      2020. 1. 7 오후 3:30:00
4      2020. 1. 8 오후 3:30:00
5      2020. 1. 9 오후 3:30:00
6     2020. 1. 10 오후 3:30:00
7     2020. 1. 13 오후 3:30:00
8     2020. 1. 14 오후 3:30:00
9     2020. 1. 15 오후 3:30:00
10    2020. 1. 16 오후 3:30:00
11    2020. 1. 17 오후 3:30:00
12    2020. 1. 20 오후 3:30:00
13    2020. 1. 21 오후 3:30:00
14    2020. 1. 22 오후 3:30:00
15    2020. 1. 23 오후 3:30:00
16    2020. 1. 28 오후 3:30:00
17    2020. 1. 29 오후 3:30:00
18    2020. 1. 30 오후 3:30:00
19    2020. 1. 31 오후 3:30:00
Name: Date, dtype: object

In [ ]:
stock["kospi"].sort_values()  # 값에따라 정렬. 값이 높은거->낮은거

19    2119.01
18    2148.00
4     2151.31
2     2155.07
0     2175.17
3     2175.54
1     2176.46
16    2176.72
17    2185.28
5     2186.45
6     2206.39
7     2229.26
9     2230.98
8     2238.88
13    2239.69
15    2246.13
10    2248.05
11    2250.57
12    2262.64
14    2267.25
Name: kospi, dtype: float64

- unique
  - 중복되는 값을 제거하고 유일한 값만 담고있는 **Series**를 반환.
  - 시리즈만 됨.

In [ ]:
obj = pd.Series([2, 1, 3, 3, 1, 5, np.nan, 1, 2])
obj

# Nan : Not a Number

0    2.0
1    1.0
2    3.0
3    3.0
4    1.0
5    5.0
6    NaN
7    1.0
8    2.0
dtype: float64

In [ ]:
obj.isnull().sum()

1

In [ ]:
obj.unique()
# Series밖에 안됨. 데이터 프레임에서는 안됨.
# But!!
# 데이터프레임에서 시리즈를 만든다면 유니크 사용할 수 있음.

array([ 2.,  1.,  3.,  5., nan])

In [ ]:
stock["kospi"].unique    # 이건 Series

<bound method Series.unique of 0     2175.17
1     2176.46
2     2155.07
3     2175.54
4     2151.31
5     2186.45
6     2206.39
7     2229.26
8     2238.88
9     2230.98
10    2248.05
11    2250.57
12    2262.64
13    2239.69
14    2267.25
15    2246.13
16    2176.72
17    2185.28
18    2148.00
19    2119.01
Name: kospi, dtype: float64>

- Value_counts
  - 숫자에 대해서 하는것

In [ ]:
obj.value_counts()

1.0    3
2.0    2
3.0    2
5.0    1
dtype: int64

In [ ]:
obj.value_counts(normalize=True)
# normalize : 0과 1 사이로 만드는것. 다 같은수로 나눠버림(?)
# 데이터의 크기가 서로 다른 자료를 비교할때 쓰임

1.0    0.375
2.0    0.250
3.0    0.250
5.0    0.125
dtype: float64

In [ ]:
obj.sort_values()

1    1.0
4    1.0
7    1.0
0    2.0
8    2.0
2    3.0
3    3.0
5    5.0
6    NaN
dtype: float64

In [ ]:
obj1 = pd.Series([1,2,3,-1,-2], index=list('adebc'))
obj1

a    1
d    2
e    3
b   -1
c   -2
dtype: int64

In [ ]:
obj1.sort_values()

c   -2
b   -1
a    1
d    2
e    3
dtype: int64

In [ ]:
obj1.sort_index()

# 인덱스보다는 벨류즈를 더 많이 씀. 인덱스를 정렬해봤자 할게 별로 없어...

a    1
b   -1
c   -2
d    2
e    3
dtype: int64

In [ ]:
obj1.sort_index(ascending=False)

e    3
d    2
c   -2
b   -1
a    1
dtype: int64

In [ ]:
obj2 = pd.Series([1,2,3,-1,-2], index=list('가마나라다'))
obj2

가    1
마    2
나    3
라   -1
다   -2
dtype: int64

In [ ]:
obj2.sort_index(ascending=False) # 내림차순

마    2
라   -1
다   -2
나    3
가    1
dtype: int64

- frame

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape(3,3), index=list('abc'), columns=list('edf'))
frame

e  d  f
a  0  1  2
b  3  4  5
c  6  7  8

In [ ]:
frame.sort_index()

e  d  f
a  0  1  2
b  3  4  5
c  6  7  8

In [ ]:
frame.sort_index(axis=1)

# axis=1 열로 인식/ 0이면 행으로 인식
# 판다스와 넘피가 반대로 돌아감

d  e  f
a  1  0  2
b  4  3  5
c  7  6  8

In [ ]:
frame.mean()

e    3.0
d    4.0
f    5.0
dtype: float64

In [ ]:
frame.mean(axis=0)

e    3.0
d    4.0
f    5.0
dtype: float64

In [ ]:
frame.mean(axis=1)

a    1.0
b    4.0
c    7.0
dtype: float64

아직까지는 같음. 그런데 하다보면 달라짐?
지금은 신경쓰지 말자.
다음에 더 배우면서 알아보자

In [ ]:
frame.sort_values(by='e',ascending=False)
# by=''  : ''안의 내용을 기준으로 분류해라

e  d  f
c  6  7  8
b  3  4  5
a  0  1  2

In [ ]:
frame.sort_values(by=['e','f'],ascending=[False,True]) # 이런식으로 각각 조건을 줄 수도 있음

e  d  f
c  6  7  8
b  3  4  5
a  0  1  2

- map
  - Series의 각각의 element들을 다른 어떤 값으로 대체하는 역할

In [4]:
import pandas as pd

In [ ]:
series = pd.Series([100,200,300])
series

In [ ]:
series.map({100:'C',200:'B',300:'A'})

In [ ]:
series.map('${}'.format)

In [ ]:
series.map('{}달러'.format)

In [ ]:
import numpy as np
f = lambda x : np.add(x,3)
series.map(f)

- apply
  - map보다 적용할 수 있는 범위가 더 큼

In [11]:
import pandas as pd
s = pd.Series([20,21,12], index=["London","New York","Helsinki"])
s

London      20
New York    21
Helsinki    12
dtype: int64

In [12]:
def sub_custom_value(x,val):
  return x-val

In [ ]:
s.apply(sub_custom_value,args=(10,))  #주의사항 : 10 뒤에 (10, )처럼 가변공간을 줘야함.

In [14]:
def add_custom_values(x,**kwargs):
  for month in kwargs:
    x += kwargs[month]
  return x
# 원래 데이터에 month가 없는데 억지로 넣으면 일단 돌아가긴 하는데 답이 이상하게 나옴
# 원래 데이터를 바꿀 수 없음.(kwarge는 딕셔너리만 받을 수 있음. 딕셔너리는 수정 불가)
# 함수 쓸 때 주의하기!

In [15]:
s.apply(add_custom_values, june=30, july=20, august=25)  # 답이 이상하게 나옴.10씩 세번 돌아가며 더해짐.

London      95
New York    96
Helsinki    87
dtype: int64

In [16]:
s.apply(add_custom_values, june=30, july=20,august=25)

London      95
New York    96
Helsinki    87
dtype: int64

- axis 별로 apply를 적용 가능

In [17]:
frame = pd.DataFrame(np.arange(12).reshape(3,4), columns = list("abcd"))
frame

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [18]:
frame.apply(lambda x : x.max() - x.min()) # axis = 0  -> default 값
# default 값 : 별도 설정 하지 않은 '초기값'. 즉, 기본설정값을 의미

a    8
b    8
c    8
d    8
dtype: int64

In [19]:
frame.apply(lambda x : x.max() - x.min(), axis = 1)

0    3
1    3
2    3
dtype: int64

- applymap
  - 모든 원소에 원소별로 함수에 적용

In [20]:
frame.applymap(lambda x : x**2)

a   b    c    d
0   0   1    4    9
1  16  25   36   49
2  64  81  100  121

- drop
  - row나 column에서 특정한 label을 삭제하는 함수

In [22]:
frame = pd.DataFrame(np.arange(16).reshape(4,4), index=['r1','r2','r3','r4'], columns = ['c1','c2','c3','c4'])
frame

c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

In [ ]:
frame.drop('r1')

In [ ]:
frame.drop('c1', axis = 1) 
# axis = 1을 안써주면 키에러남. axis를 찾을 수 없다고 나옴. 그럼 axis = 1를 써주면 됨.

In [ ]:
frame1 = frame.drop('r1')  # 새 변수 만들어서 드롭한거 저장하면 원본 데이터 남길 수 있음.
frame1

In [ ]:
#frame.drop('r1',inplace=True)   # 이렇게 하면 덮어씀. 원본데이터 날라가므로 주의!

In [ ]:
frame.drop(columns=['c3','c4'])

- 데이터 병합
  - concat

In [25]:
s1 = pd.Series([100,200],index=['c','d'])
s2 = pd.Series([300,300,300],index=['c','d','e'])
s3 = pd.Series([500,600], index=['f','g'])

print(s1,s2,s3, sep='\n\n')

c    100
d    200
dtype: int64

c    300
d    300
e    300
dtype: int64

f    500
g    600
dtype: int64


In [24]:
pd.concat([s1,s2,s3])

c    100
d    200
c    300
d    300
e    300
f    500
g    600
dtype: int64

In [26]:
pd.concat([s1,s2], axis=1) #SQL의 outer join(합집합)으로 돌아감.

0    1
c  100.0  300
d  200.0  300
e    NaN  300

- Merge
   - key를 이용해 데이터의 row를 기준으로 연결시켜 합침(SQL의 join과 유사)

In [31]:
import numpy as np
data1 = pd.DataFrame({'id':['01','02','03','04','05','06'],
                      'col1':np.random.randint(0,50,6), 
                      'col2':np.random.randint(1000,2000,6)})
data1

id  col1  col2
0  01     3  1782
1  02    41  1606
2  03    13  1322
3  04    31  1232
4  05    13  1190
5  06    18  1601

In [32]:
data2 = pd.DataFrame({'id':['04','05','06','07'], 
                      'col1':np.random.randint(100,5000,4)})
data2

id  col1
0  04  3959
1  05  3709
2  06  4909
3  07  3359

In [33]:
# inner join(교집합)
pd.merge(data1,data2,on='id')    # on : 기준

id  col1_x  col2  col1_y
0  04      31  1232    3959
1  05      13  1190    3709
2  06      18  1601    4909

In [34]:
# how : 어떤 방식으로 병합할 것인가? {inner, outer, left, right}
pd.merge(data1,data2,on='id', how='left')

id  col1_x  col2  col1_y
0  01       3  1782     NaN
1  02      41  1606     NaN
2  03      13  1322     NaN
3  04      31  1232  3959.0
4  05      13  1190  3709.0
5  06      18  1601  4909.0

In [35]:
# outer join(합집합)
pd.merge(data1,data2,on='id', how='outer')

id  col1_x    col2  col1_y
0  01     3.0  1782.0     NaN
1  02    41.0  1606.0     NaN
2  03    13.0  1322.0     NaN
3  04    31.0  1232.0  3959.0
4  05    13.0  1190.0  3709.0
5  06    18.0  1601.0  4909.0
6  07     NaN     NaN  3359.0

- missing data
  - dropna : 결측치를 삭제(결측치가 있는것을 삭제)

In [38]:
obj = pd.Series(['apple','mango', np.nan, None, 'peach',1])
obj

0    apple
1    mango
2      NaN
3     None
4    peach
5        1
dtype: object

In [39]:
obj.dropna()

0    apple
1    mango
4    peach
5        1
dtype: object

In [40]:
frame = pd.DataFrame([[np.nan, np.nan, np.nan, np.nan],
                      [10,5,40,6],
                      [5,2,30,8],
                      [15,3,10, np.nan]], 
                     columns = ['x1', 'x2', 'x3', 'x4'])
frame

x1   x2    x3   x4
0   NaN  NaN   NaN  NaN
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0
3  15.0  3.0  10.0  NaN

In [ ]:
frame.dropna() # 이렇게 하면 많이 날아감. (nan이 있는 줄 다 날라감)

In [42]:
frame.dropna(how='any')
# how에는 any 와 all이 있음.
# all이 들어가면 행과 열이 모두 있을때만 삭제됨.

x1   x2    x3   x4
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0

In [41]:
frame.dropna(how='all')
# how에는 any 와 all이 있음.
# all이 들어가면 행과 열이 모두 있을때만 삭제됨.

x1   x2    x3   x4
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0
3  15.0  3.0  10.0  NaN

- 결측치를 채우는 방법
  - fillna

In [43]:
frame

x1   x2    x3   x4
0   NaN  NaN   NaN  NaN
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0
3  15.0  3.0  10.0  NaN

In [45]:
frame.fillna(0)   # 결측난 곳 0으로 채우기
#method : ffill(앞에서채우기), bfill(밑에서채우기), backfill(뒤에서 채우기), pad(두껍게), None

x1   x2    x3   x4
0   0.0  0.0   0.0  0.0
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0
3  15.0  3.0  10.0  0.0

In [46]:
frame.fillna({'x1':10, 'x3':3})

x1   x2    x3   x4
0  10.0  NaN   3.0  NaN
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0
3  15.0  3.0  10.0  NaN

In [47]:
frame.isna().sum()

x1    1
x2    1
x3    1
x4    2
dtype: int64

- 중복제거
  1. duplicated():각 row가 중복(True)인지 아닌지(False) 알려주는 불리언 Series 변환
  2. drop_duplicates() : duplicated를 적용한 결과가 False인것들만 모아서 dataframe 반환

In [48]:
data = pd.DataFrame({'id':['0001','0002','0003','0001'],
                     'name': ['a','b','c','a']})
data

id name
0  0001    a
1  0002    b
2  0003    c
3  0001    a

In [49]:
data.duplicated()    # 중복체크(True -> 중복있음)

0    False
1    False
2    False
3     True
dtype: bool

In [ ]:
data.drop_duplicates()  # 중복을 삭제

- cut 함수

In [50]:
ages = [20,35,67,39,59,44,56,77,28,80,32,46,52,19,33,5,15,50,29,21,32,48,85,66,45,32,10,]
bins = [0,20,40,60,100]  # 인터벌에 존재한다??

In [51]:
cuts = pd.cut(ages,bins) # 나이가 어느 인터벌에 존재하는지 모여줌??
cuts

[(0, 20], (20, 40], (60, 100], (20, 40], (40, 60], ..., (60, 100], (60, 100], (40, 60], (20, 40], (0, 20]]
Length: 27
Categories (4, interval[int64, right]): [(0, 20] < (20, 40] < (40, 60] < (60, 100]]

In [52]:
cuts.categories   # cut 메소드의 결과는 Categorical이라는 특수 객체에 존재

IntervalIndex([(0, 20], (20, 40], (40, 60], (60, 100]], dtype='interval[int64, right]')

In [53]:
cuts.codes

array([0, 1, 3, 1, 2, 2, 2, 3, 1, 3, 1, 2, 2, 0, 1, 0, 0, 2, 1, 1, 1, 2,
       3, 3, 2, 1, 0], dtype=int8)

In [54]:
# 구간을 균등한 길이로 나눔1
pd.cut(ages,4, precision = 1).value_counts()  # 4구간으로 나눔
# precision : 소수점 자리수, 3이면 소수점 세번째에서 반올림.

(4.9, 25.0]      6
(25.0, 45.0]    10
(45.0, 65.0]     6
(65.0, 85.0]     5
dtype: int64

In [55]:
# 구간을 균등한 길이로 나눔2   -  이걸 좀 더 많이 씀.
pd.qcut(ages,4).value_counts()

(4.999, 28.5]    7
(28.5, 39.0]     7
(39.0, 54.0]     6
(54.0, 85.0]     7
dtype: int64

categorical variable : 문자형 변수

- get_dummies

In [56]:
df = pd.DataFrame({'col1': [10,20,30],
                   'col2': ['a', 'b', 'c']})
df

col1 col2
0    10    a
1    20    b
2    30    c

In [ ]:
pd.get_dummies(df)

In [ ]:
df = pd.DataFrame({
    'col1':['001','002','003','004','005','006'],
    'col2' :[10,20,30,40,50,60],
    'col3' : ['서울시','경기도','서울시','제주도','경기도','서울시']    
})
df
# 0으로 표시되는 빈 데이터가 많아짐. (sparse matrix 라고 함.)

In [ ]:
pd.get_dummies(df)

-groupby

In [4]:
import pandas as pd

kbo = pd.read_csv('/content/kbo.csv')
kbo

연도  순위    팀  경기수   승   패  무     승률   게임차
0   2019   1   두산  144  88  55  1  0.615   0.0
1   2019   2   키움  144  86  57  1  0.601   2.0
2   2019   3   SK  144  88  55  1  0.615   0.0
3   2019   4   LG  144  79  64  1  0.552   9.0
4   2019   5   NC  144  73  69  2  0.514  14.5
5   2019   6   KT  144  71  71  2  0.500  16.5
6   2019   7  KIA  144  62  80  2  0.437  25.5
7   2019   8   삼성  144  60  83  1  0.420  28.0
8   2019   9   한화  144  58  86  0  0.403  30.5
9   2019  10   롯데  144  48  93  3  0.340  39.0
10  2018   1   두산  144  93  51  0  0.646 -14.5
11  2018   2   SK  144  78  65  1  0.545   0.0
12  2018   3   한화  144  77  67  0  0.535   1.5
13  2018   4   넥센  144  75  69  0  0.521   3.5
14  2018   5  KIA  144  70  74  0  0.486   8.5
15  2018   5   삼성  144  68  72  4  0.486   8.5
16  2018   7   롯데  144  68  74  2  0.479   9.5
17  2018   8   LG  144  68  75  1  0.476  10.0
18  2018   9   KT  144  59  82  3  0.418  18.0
19  2018  10   NC  144  58  85  1  0.406  20.0
20  2017   1  KIA  144  87  56  1  0.608   0.0
21  2017   2   두산  144  84  57  3  0.596   2.0
22  2017   3   롯데  144  80  62  2  0.563   6.5
23  2017   4   NC  144  79  62  3  0.560   7.0
24  2017   5   SK  144  75  68  1  0.524  12.0
25  2017   6   LG  144  69  72  3  0.489  17.0
26  2017   7   넥센  144  69  73  2  0.486  17.5
27  2017   8   한화  144  61  81  2  0.430  25.5
28  2017   9   삼성  144  55  84  5  0.396  30.0
29  2017  10   KT  144  50  94  0  0.347  37.5

In [58]:
kbo.shape

(30, 9)

In [59]:
kbo.columns

Index(['연도', '순위', '팀', '경기수', '승', '패', '무', '승률', '게임차'], dtype='object')

In [ ]:
kbo['팀'].unique   #중복제거

In [5]:
kbo.info()  # '팀' object로 나옴. 이것은 문자라는 소리임.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   연도      30 non-null     int64  
 1   순위      30 non-null     int64  
 2   팀       30 non-null     object 
 3   경기수     30 non-null     int64  
 4   승       30 non-null     int64  
 5   패       30 non-null     int64  
 6   무       30 non-null     int64  
 7   승률      30 non-null     float64
 8   게임차     30 non-null     float64
dtypes: float64(2), int64(6), object(1)
memory usage: 2.2+ KB


In [62]:
kbo.describe()

연도         순위    경기수          승          패          무  \
count    30.000000  30.000000   30.0  30.000000  30.000000  30.000000   
mean   2018.000000   5.466667  144.0  71.200000  71.200000   1.600000   
std       0.830455   2.921187    0.0  11.871147  11.591912   1.275769   
min    2017.000000   1.000000  144.0  48.000000  51.000000   0.000000   
25%    2017.000000   3.000000  144.0  61.250000  62.500000   1.000000   
50%    2018.000000   5.000000  144.0  70.500000  71.500000   1.000000   
75%    2019.000000   8.000000  144.0  79.000000  80.750000   2.000000   
max    2019.000000  10.000000  144.0  93.000000  94.000000   5.000000   

              승률        게임차  
count  30.000000  30.000000  
mean    0.499800  12.833333  
std     0.082079  12.576204  
min     0.340000 -14.500000  
25%     0.431750   2.375000  
50%     0.494500   9.750000  
75%     0.558000  19.500000  
max     0.646000  39.000000

In [63]:
kbo.isna().sum()

연도     0
순위     0
팀      0
경기수    0
승      0
패      0
무      0
승률     0
게임차    0
dtype: int64

- groupby를 하여 group으로 묶인 Groupby 객체를 반환
이 객체는 그룹연산을 위해 필요한 모든 정보를 가지고 있음.

In [64]:
kbo.groupby('팀')

In [ ]:
kbo.groupby('팀').count()
# 팀 이름이 넥센에서 키움으로 바뀜. 같은팀이야~

In [ ]:
# 연도별로 묶을수도 있음
kbo.groupby(['연도','팀']).sum()

In [ ]:
kbo.groupby('팀')['승률'].max()

In [ ]:
kbo.groupby(['연도','팀'])['승률','순위'].max()
#연도와 팀을 묶은 후 승률과 순위의 맥스값을 보여줘

In [74]:
grouped = kbo.groupby('팀')

for name,group in grouped:
    print(name)
    print(group)

    print('-'*50)

# 팀별로 묶어서 볼 수 있음
# 근데 에러나네.. 왜? :  , 를 . 로 잘못씀

KIA
      연도  순위    팀  경기수   승   패  무     승률   게임차
6   2019   7  KIA  144  62  80  2  0.437  25.5
14  2018   5  KIA  144  70  74  0  0.486   8.5
20  2017   1  KIA  144  87  56  1  0.608   0.0
--------------------------------------------------
KT
      연도  순위   팀  경기수   승   패  무     승률   게임차
5   2019   6  KT  144  71  71  2  0.500  16.5
18  2018   9  KT  144  59  82  3  0.418  18.0
29  2017  10  KT  144  50  94  0  0.347  37.5
--------------------------------------------------
LG
      연도  순위   팀  경기수   승   패  무     승률   게임차
3   2019   4  LG  144  79  64  1  0.552   9.0
17  2018   8  LG  144  68  75  1  0.476  10.0
25  2017   6  LG  144  69  72  3  0.489  17.0
--------------------------------------------------
NC
      연도  순위   팀  경기수   승   패  무     승률   게임차
4   2019   5  NC  144  73  69  2  0.514  14.5
19  2018  10  NC  144  58  85  1  0.406  20.0
23  2017   4  NC  144  79  62  3  0.560   7.0
--------------------------------------------------
SK
      연도  순위   팀  경기수   승   패  무     승률 

In [75]:
grouped.get_group('한화')

연도  순위   팀  경기수   승   패  무     승률   게임차
8   2019   9  한화  144  58  86  0  0.403  30.5
12  2018   3  한화  144  77  67  0  0.535   1.5
27  2017   8  한화  144  61  81  2  0.430  25.5